name: CI-by-Aleksei-Alekseichik

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name   : find-tabs
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: find
        id: files
        uses: jitterbit/get-changed-files@v1
        
      - name: tab
        run: |
         for changed_file in ${{ steps.files.outputs.all }}; do
         echo "Do something with this ${changed_file}."
         grep -P '\t' $files | cut -f 1 -d ':' | sort | uniq -c | sort -nr | head > output.log
         done
         
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: output.log
