name: CI-by-Aleksei-Alekseichik

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name   : find-tabs
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: List all added files
        run : |
         for file in ${{ steps.changed-files.outputs.added_files }}; do
         grep "$(printf '\t')" $files | cut -f 1 -d ':' | sort | uniq -c | sort -nr | head > output.log
         done
         
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: output.log
